"""empty message

Revision ID: 1d9a2b4f1d90
Revises: 
Create Date: 2019-04-14 01:00:49.178919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9a2b4f1d90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('cl', sa.String(length=15), nullable=True),
    sa.Column('pos', sa.Float(), nullable=True),
    sa.Column('neg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_timestamp'), 'result', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_timestamp'), table_name='result')
    op.drop_table('result')
    # ### end Alembic commands ###
