"""empty message

Revision ID: 96523e160933
Revises: 
Create Date: 2019-04-08 00:10:00.587371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96523e160933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('p_pos', sa.Integer(), nullable=True),
    sa.Column('p_neg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_timestamp'), 'results', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_timestamp'), table_name='results')
    op.drop_table('results')
    # ### end Alembic commands ###
